### ISSUE TITLE
<test_diagnostic> doesn't support nested YAML format

### ISSUE THREAD

**Issue by kylewelsby** [vincent-psarga/ruby-tap-parser#1]
Test Diagnostic output removes nesting.

input 

```
TAP version 13
not ok - paginate 4
  ---
  uuid: null
  pageNumber: 4
  cacheId: null
  url: 'http://example.com/page4.html'
  screenshots:
      full: 'http://test.host/null|4.jpg'
      thumbnail: 'http://test.host/null|4-thumb.jpg'
  error:
      message: error.navigation.duplicate
  ...
1..1
```

expected

``` YAML

---
uuid: 3a4dc4d2-c2f6-4c6c-bf66-3d21276a43af
pageNumber: 1
cacheId: 1868b791-6ffa-43d7-baf1-90b9307d3c3d|1
url: 'http://www.cdapresents.com/Anaheim2015/ExhibitHall.aspx'
screenshots:
  full: 'http://localhost:3351/screen-grabs/1868b791-6ffa-43d7-baf1-90b9307d3c3d|1.jpeg'
  thumbnail: 'http://localhost:3351/screen-grabs/1868b791-6ffa-43d7-baf1-90b9307d3c3d|1-thumb.jpeg'
  quick: 'http://localhost:3351/screen-grabs/1868b791-6ffa-43d7-baf1-90b9307d3c3d|1-quick.jpeg'
error:
  message: error.navigation.duplicate
```

actual 

``` YAML

---
uuid: 3a4dc4d2-c2f6-4c6c-bf66-3d21276a43af
pageNumber: 1
cacheId: 1868b791-6ffa-43d7-baf1-90b9307d3c3d|1
url: 'http://www.cdapresents.com/Anaheim2015/ExhibitHall.aspx'
screenshots:
full: 'http://localhost:3351/screen-grabs/1868b791-6ffa-43d7-baf1-90b9307d3c3d|1.jpeg'
thumbnail: 'http://localhost:3351/screen-grabs/1868b791-6ffa-43d7-baf1-90b9307d3c3d|1-thumb.jpeg'
quick: 'http://localhost:3351/screen-grabs/1868b791-6ffa-43d7-baf1-90b9307d3c3d|1-quick.jpeg'
error:
message: error.navigation.duplicate
```
